const pressures = [
  ['01','3 in 5 dentists','Staffing pressure is consuming the front desk.','Dentists identified recruiting and retaining staff as a leading concern.','RaySky handles repetitive calls, messages, summaries, and follow-up, then hands exceptions to a person with the full context.','More staff capacity for patients in the clinic','ADA HPI, 2024','https://adanews.ada.org/new-dentist/2025/march/staffing-shortages-top-expected-challenges-this-year'],
  ['02','80% of practices','Short-notice cancellations break a carefully planned day.','Dental practices cite last-minute cancellations as the main reason schedules are incomplete.','RaySky detects openings, checks provider, procedure, operatory, and appointment-length rules, then contacts the best waitlist matches.','More protected chair time and completed visits','ADA Commons, 2024','https://commons.ada.org/mddsarticulator/vol29/iss4/8/'],
  ['03','Cost, fear, convenience','Patients hesitate for reasons that a generic reminder cannot solve.','Affordability, dental fear, and finding a convenient time remain leading barriers to care.','RaySky gives approved answers, shares clinic-approved payment options, finds a suitable time, and moves clinical questions to your team.','A clearer, more respectful path back to care','ADA HPI, 2026','https://www.ada.org/resources/research/health-policy-institute/dental-care-market'],
  ['04','More than half','Insurance work delays answers, payment, and patient decisions.','Dentists report low reimbursement, denied coverage, delayed payments, and public-program administration as major challenges.','RaySky surfaces eligibility exceptions, routes claims and coverage tasks, uses approved explanations, and escalates anything that needs staff judgment.','Fewer unresolved coverage and payment tasks','ADA HPI, 2024','https://adanews.ada.org/new-dentist/2025/march/staffing-shortages-top-expected-challenges-this-year'],
  ['05','The first week matters','Unscheduled treatment loses momentum after the patient leaves.','ADA practice guidance notes that patients needing extensive care should return promptly to discuss options.','RaySky organizes pending care by urgency, follows approved scripts, answers nonclinical questions, shares financing resources, and books the next step.','More treatment conversations reach a decision','ADA Practice Guidance','https://www.ada.org/resources/practice/practice-management/accepted-treatment'],
  ['06','Margins under pressure','Rising overhead makes every lost opportunity more expensive.','Dental practices report higher expenses alongside pressure on patient volume and reimbursement.','RaySky ranks missed calls, recall, treatment, balances, and acquisition by recoverable value, then links action to completed outcomes.','A measurable return from opportunities already created','ADA HPI, 2025','https://adanews.ada.org/huddles/dental-fiscal-squeeze-continues-into-2026/'],
] as const;

export default function ClinicPainMap() {
  return <section className="clinic-pressure"><div className="rl-shell">
    <header className="pressure-intro reveal"><span>What dental clinics are carrying</span><h2>Your team is not failing. <em>The operating model is asking too much of too few people.</em></h2><p>RaySky closes the gaps between patient intent, staff capacity, clinical rules, and payment. Every workflow ends in a completed action, a human handoff, or a visible exception.</p></header>
    <div className="pressure-grid">{pressures.map(([number,signal,pain,evidence,solution,outcome,source,href]) => <article className="pressure-card reveal" key={number}>
      <div className="pressure-index"><i>{number}</i><strong>{signal}</strong></div><h3>{pain}</h3><p className="pressure-evidence">{evidence}</p>
      <div className="pressure-answer"><span>What RaySky changes</span><p>{solution}</p><strong>✓ {outcome}</strong></div><a href={href} target="_blank" rel="noreferrer">Source: {source} ↗</a>
    </article>)}</div>
    <div className="patient-path reveal"><header><span>The patient journey</span><strong>Remove friction at every decision, not only at the first call.</strong></header><div>{['Finds your clinic','Asks about care','Understands cost and coverage','Chooses a time','Receives helpful follow-up','Completes care'].map((item,index)=><span key={item}><i>{String(index+1).padStart(2,'0')}</i>{item}</span>)}</div><p>RaySky keeps the next step moving while preserving consent, clinical boundaries, and the option to speak with your team.</p></div>
  </div></section>;
}
