import type { Metadata } from 'next';
import RevenueAudit from './RevenueAudit';
import LuxuryLayer from './LuxuryLayer';
import VIPConsultation from './VIPConsultation';
import GrowthEngine from './GrowthEngine';
import ClinicPainMap from './ClinicPainMap';
import './revenue-leak.css';

export const metadata: Metadata = {
  title: 'Free Clinic Revenue Audit | RaySky',
  description: 'Audit patient acquisition, ads, landing pages, lead response, scheduling, recall, treatment coordination, insurance friction, and collections in two minutes.',
  alternates: { canonical: '/revenue-audit' },
  openGraph: { title: 'See Where Your Clinic Revenue Is Being Left Behind', description: 'Run a two minute audit across your clinic revenue cycle.', url: '/revenue-audit' },
};

const Tick = () => <i className="rl-tick" aria-hidden="true">✓</i>;

export default function RevenueLeakAuditPage() {
  return <main className="revenue-leak-page luxury-revenue-page">
    <LuxuryLayer />
    <header className="rl-header"><div className="rl-shell"><a className="rl-brand" href="/" aria-label="RaySky home"><img className="rl-brand-mark" src="/raysky-mark.png" alt=""/><span>RaySky<small>Revenue OS for clinics</small></span></a><div className="rl-header-proof"><span><i /> Live inside your PMS</span><span><i /> Human escalation</span></div><a href="#revenue-audit">Start revenue audit <b>↗</b></a></div></header>
    <section className="rl-hero"><div className="rl-film-grain" /><div className="rl-shell rl-hero-grid"><div className="rl-hero-copy"><span className="rl-eyebrow">The revenue operating system for dental clinics</span><h1>More patients complete care. <em>Your team gets capacity back.</em></h1><p>RaySky connects patient acquisition, scheduling, recall, treatment follow-up, insurance tasks, and payments in one closed loop. It completes routine work, escalates exceptions with context, and shows what became attended care and measurable revenue.</p><div className="rl-actions"><a href="#revenue-audit">Find my clinic’s revenue gaps <b>→</b></a><span>Takes 2 minutes<br/>Results before contact details</span></div><div className="rl-integrations"><span>Works with</span><strong>Dentrix</strong><strong>Eaglesoft</strong><strong>Open Dental</strong><strong>Curve</strong></div></div><div className="rl-hero-stage"><div className="schedule-window"><div className="schedule-top"><span><i /> Live schedule protection</span><small>Wednesday</small></div><div className="schedule-line"><b>1:00</b><span>Hygiene visit</span><em>Confirmed</em></div><div className="schedule-line empty"><b>2:30</b><span>Opening detected</span><em>Matching</em></div><div className="schedule-line recovered"><b>2:30</b><span>Maria S. · Hygiene</span><em><Tick /> Refilled</em></div><div className="schedule-result"><span>Chair time protected</span><strong>+$550</strong><small>Written to practice system</small></div></div><div className="rl-orbit one"/><div className="rl-orbit two"/></div></div><div className="rl-shell rl-audit-wrap"><RevenueAudit /></div></section>
    <section className="rl-epiphany"><div className="rl-shell"><header className="rl-section-head reveal"><span>The revenue opportunity</span><h2>Growth should not stop at lead generation. <em>Complete more of every opportunity you create.</em></h2><p>Your staff can only answer one patient at a time. RaySky watches the gaps between demand, care, and payment so the next action does not depend on memory or spare time.</p></header><div className="rl-leak-grid"><article className="reveal"><i>01</i><div><span>A patient calls while the team is helping someone in person.</span><strong>The call waits. The patient does not.</strong></div><small>Missed demand</small></article><article className="reveal"><i>02</i><div><span>A cancellation opens tomorrow at 2:30 PM.</span><strong>The perfect waitlist match never hears about it.</strong></div><small>Unused capacity</small></article><article className="reveal"><i>03</i><div><span>A patient says they need time to consider treatment.</span><strong>The next helpful conversation never happens.</strong></div><small>Uncompleted care</small></article></div><div className="rl-leak-note"><span>One missed call. One open chair. One unfinished follow up.</span><strong>Small moments become a monthly pattern.</strong><small>Your audit uses your own clinic inputs. It does not rely on generic industry loss claims.</small></div></div></section>
    <ClinicPainMap />
    <GrowthEngine />
    <section className="rl-protocols"><div className="rl-shell"><header className="rl-section-head inverted reveal"><span>The RaySky protocols</span><h2>Stop chasing every task. Let the system <em>move the right patient forward.</em></h2></header><div className="rl-protocol-list">
      <article className="protocol reveal"><div className="protocol-copy"><span>Protocol 01 · Schedule recovery</span><h3>How does an empty chair find the right patient?</h3><p>RaySky detects the opening, checks the clinical rules, finds eligible patients, starts the outreach, and writes the confirmed appointment back to your system.</p><strong><Tick /> Your daily production has a recovery plan</strong></div><div className="protocol-visual waitlist-visual"><div className="visual-label"><i /> Live cancellation recovery</div><div className="slot-card lost"><span>2:30 PM</span><strong>Opening detected</strong><small>Hygiene · 60 min</small></div><div className="match-line"><span>Provider</span><b>✓</b><span>Procedure</span><b>✓</b><span>Length</span><b>✓</b></div><div className="slot-card won"><span>2:30 PM</span><strong>Maria S. confirmed</strong><small>Appointment written to PMS</small></div></div></article>
      <article className="protocol reverse reveal"><div className="protocol-copy"><span>Protocol 02 · Patient capture</span><h3>What happens when the next high value patient calls at 2:00 AM?</h3><p>RaySky answers, understands the request, checks availability, and secures the next step. Your team receives the context when a human needs to take over.</p><strong><Tick /> Every conversation has an owner and a next action</strong></div><div className="protocol-visual conversation-visual"><div className="visual-label"><i /> After hours · Live</div><div className="voice-wave">{[19,31,23,45,28,52,34,49,22,40,18,33].map((height,index)=><i key={index} style={{height}} />)}</div><div className="conversation-copy"><span>Patient</span><p>I need an emergency appointment tomorrow.</p><span>RaySky</span><p>I can help. Let me check the clinic’s emergency blocks.</p></div><div className="conversation-status"><Tick /><strong>Urgent visit reserved</strong><small>Staff review queued</small></div></div></article>
      <article className="protocol reveal"><div className="protocol-copy"><span>Protocol 03 · Hidden cash recovery</span><h3>What if the next treatment conversation happened at exactly the right time?</h3><p>RaySky follows approved policies for pending care and eligible balances. It answers nonclinical questions, shares approved financing resources, sends secure links, and escalates exceptions.</p><strong><Tick /> Helpful follow up without pressure or improvisation</strong></div><div className="protocol-visual cash-visual"><div className="visual-label"><i /> Opportunity ledger</div><div className="ledger-total"><span>Eligible opportunity</span><strong>$24,800</strong><small>Illustrative view</small></div><div className="ledger-row"><span>Treatment follow up</span><b>Consult booked</b></div><div className="ledger-row"><span>Patient balance</span><b>Link opened</b></div><div className="ledger-row"><span>Clinical question</span><b>Escalated</b></div><div className="cash-status"><Tick /> Every action documented</div></div></article>
    </div></div></section>
    <section className="rl-integration"><div className="rl-shell rl-integration-grid"><div className="integration-copy reveal"><span>Closed loop by design</span><h2>Will this create more work for your staff?</h2><strong>No. RaySky completes the work inside the systems your team already uses.</strong><p>Every action follows your configured provider, operatory, procedure, insurance, consent, and escalation rules.</p><a href="#revenue-audit">Include my systems in the audit <b>→</b></a></div><div className="system-map reveal"><div className="system-center"><span>RaySky</span><strong>Patient signal becomes a completed task</strong><small>Controlled · Connected · Auditable</small></div><div className="system-node node-one"><span>01</span><strong>Read</strong><small>Availability and patient context</small></div><div className="system-node node-two"><span>02</span><strong>Act</strong><small>Book, follow up, or escalate</small></div><div className="system-node node-three"><span>03</span><strong>Write</strong><small>Outcome, summary, and audit trail</small></div></div></div><div className="rl-shell rl-system-list"><strong>Dentrix</strong><strong>Eaglesoft</strong><strong>Open Dental</strong><strong>Denticon</strong><strong>Curve</strong><strong>Cloud 9</strong><span>And more</span></div></section>
    <section className="luxury-signals"><div className="rl-shell"><header data-luxury-reveal><span>One intelligent layer</span><h2>Every patient signal becomes a visible next action.</h2><p>Move through each field to see how RaySky turns fragmented activity into coordinated clinic revenue.</p></header><div className="signal-grid">
      <article className="signal-card particles" tabIndex={0} data-luxury-reveal><div className="particle-field">{Array.from({length:42},(_,i)=><i key={i}/>)}</div><span>01 · Opportunity sensing</span><h3>See the moments your team cannot watch all at once.</h3><p>Ads, search, landing pages, calls, forms, cancellations, recall status, treatment, balances, and insurance exceptions enter one prioritized view.</p></article>
      <article className="signal-card morph" tabIndex={0} data-luxury-reveal><div className="morph-object"><i/><i/><i/></div><span>02 · Workflow intelligence</span><h3>Match each opportunity to the right rule and response.</h3><p>Provider, operatory, procedure, consent, and escalation logic shape every action before it reaches a patient.</p></article>
      <article className="signal-card fluid" tabIndex={0} data-luxury-reveal><div className="fluid-orb"><i/></div><span>03 · Measurable completion</span><h3>Follow the outcome all the way to verified revenue.</h3><p>Connect outreach to booked appointments, completed care, and eligible payments with a reviewable audit trail.</p></article>
    </div></div></section>
    <section className="rl-human"><div className="rl-shell rl-human-grid"><div className="human-image reveal"><img src="/clinic-front-desk.png" alt="Clinic front desk professional focused on a patient conversation"/><div><span>Human care stays human</span><strong>Your team gets time back for the patient in front of them.</strong></div></div><div className="human-copy reveal"><span>The real transformation</span><h2>A calmer desk. A fuller schedule. A result your clinic can inspect.</h2><p>RaySky is not designed to replace judgment, empathy, or clinical expertise. It removes repetitive coordination work and brings the exceptions to the right person with the full context intact.</p><div><span><Tick /><strong>Patients get a timely answer</strong></span><span><Tick /><strong>Staff stop repeating completed work</strong></span><span><Tick /><strong>Owners see the financial outcome</strong></span></div><blockquote>Measure the completed appointment, the accepted care, and the collected balance. Not just the conversation.</blockquote><small>RaySky product principle</small></div></div></section>
    <section className="rl-proof"><div className="rl-shell"><header className="rl-section-head reveal"><span>Proof before promises</span><h2>Your numbers. Your baseline. <em>Your audit trail.</em></h2><p>The estimate begins the conversation. Verified reporting comes from the clinic’s real opportunity records, completed outcomes, and financial definitions.</p></header><div className="rl-proof-board reveal"><div><span>Patient and lead opportunities</span><strong>1,240</strong><small>Sources and records reviewed</small></div><i>→</i><div><span>At risk</span><strong>186</strong><small>Baseline qualified</small></div><i>→</i><div className="active"><span>Appointments recovered</span><strong>74</strong><small>Completed and verified</small></div><i>→</i><div className="active"><span>Production linked</span><strong>$43,280</strong><small>Illustrative reporting format</small></div></div><p className="rl-proof-disclaimer">Illustrative reporting format. Not a customer result, testimonial, or performance guarantee.</p></div></section>
    <section className="credibility-wall"><div className="rl-shell"><header data-luxury-reveal><span>Credibility, made inspectable</span><h2>Trust should live in the product, not in a row of borrowed logos.</h2></header><div className="credibility-stage" data-luxury-reveal><article><span>Growth attribution</span><strong>Source to production</strong><p>Connect campaign, keyword, call, or form to booking and completed care.</p></article><article><span>Clinical boundaries</span><strong>Approved answers only</strong><p>Clinical questions move to staff with context intact.</p></article><article><span>Scheduling integrity</span><strong>Rules before booking</strong><p>Availability, provider, operatory, procedure, and duplicate checks.</p></article><article><span>Patient choice</span><strong>Consent remembered</strong><p>Opt-outs and communication controls follow every workflow.</p></article><article><span>Financial control</span><strong>No improvised advice</strong><p>Approved policies, secure links, and dispute escalation.</p></article><article><span>Attribution</span><strong>Baseline to outcome</strong><p>Every reported result links back to a qualified opportunity.</p></article></div></div></section>
    <div className="rl-shell"><VIPConsultation /></div>
    <section className="rl-final"><div className="rl-film-grain"/><div className="rl-shell reveal"><span>Start with a 2 minute audit</span><h2>How much opportunity is hiding in your schedule right now?</h2><p>Use your clinic’s numbers. See a planning estimate. Then validate the highest value workflow against your baseline and capacity.</p><a href="#revenue-audit">Run my revenue audit <b>→</b></a><div><span><Tick /> Results before contact details</span><span><Tick /> No patient data</span><span><Tick /> Human review included</span></div></div></section>
    <footer className="rl-footer rl-shell"><a className="rl-brand" href="/" aria-label="RaySky home"><img className="rl-brand-mark" src="/raysky-mark.png" alt=""/><span>RaySky<small>Revenue OS for clinics</small></span></a><p>AI revenue recovery for dental and medical clinics.</p><div><a href="https://www.raysky.ai/privacy">Privacy</a><a href="https://www.raysky.ai/terms">Terms</a><a href="mailto:hello@raysky.ai?subject=RaySky%20privacy%20and%20compliance">Privacy and compliance</a></div><small>© 2026 RaySky AI</small></footer>
    <a className="rl-sticky" href="#revenue-audit">Run my revenue audit <b>→</b></a>
  </main>;
}
