import type { Metadata } from 'next';
import LeadForm from './LeadForm';
import './ads.css';

export const metadata: Metadata = {
  title: 'Recover More Dental Appointments | RaySky',
  description: 'See how RaySky helps dental clinics recover missed calls, overdue recall, cancellations, unscheduled treatment, and patient balances.',
  alternates: { canonical: '/dental-revenue-recovery' },
  openGraph: {
    title: 'Turn Lost Dental Opportunities Into Completed Care',
    description: 'A closed-loop AI revenue system for dental clinics.',
    url: '/dental-revenue-recovery',
  },
};

const Check = () => <span className="ad-check" aria-hidden="true">✓</span>;

export default function DentalRevenueRecoveryPage() {
  return (
    <main className="ads-page">
      <nav className="ads-nav ads-shell" aria-label="Landing page navigation">
        <a className="ads-brand" href="/"><i>R</i><span>RaySky<small>Dental Revenue OS</small></span></a>
        <a className="ads-nav-cta" href="#assessment">Get my assessment <span>↗</span></a>
      </nav>
      <section className="ads-hero">
        <div className="ads-shell ads-hero-grid">
          <div className="ads-hero-copy">
            <div className="ad-eyebrow"><i /> Built for dental clinics</div>
            <h1>Turn missed patient opportunities into <em>completed care.</em></h1>
            <p>RaySky follows up, books, updates your practice system, and shows exactly what became an attended appointment, accepted treatment, or collected balance.</p>
            <div className="ads-proof-row"><span><Check /> Works with your PMS</span><span><Check /> Human escalation</span><span><Check /> Auditable outcomes</span></div>
            <a className="ad-primary ad-mobile-cta" href="#assessment">See my clinic’s opportunity <b>↗</b></a>
          </div>
          <div id="assessment"><LeadForm /></div>
        </div>
      </section>
      <section className="ad-integrations" aria-label="Practice management system compatibility"><div className="ads-shell"><span>Connects with the systems your team already knows</span><div><strong>Dentrix</strong><strong>Eaglesoft</strong><strong>Open Dental</strong><strong>Denticon</strong><strong>Curve</strong><strong>Cloud 9</strong></div></div></section>
      <section className="ad-section ad-problem ads-shell">
        <header className="ad-section-heading"><span>Revenue is already reaching your clinic</span><h2>The problem is what happens <em>between interest and completed care.</em></h2><p>Calls go unanswered. Recall lists grow. Treatment stays unscheduled. Cancellations leave gaps. Balances age. RaySky gives every opportunity a next action—and your team a clear outcome.</p></header>
        <div className="leakage-grid"><article><span>01</span><h3>Demand slips away</h3><p>Missed calls and web leads wait too long for a response.</p><strong>Recover the conversation</strong></article><article><span>02</span><h3>Chair time goes unused</h3><p>Recall, cancellations, and waitlists live in separate workflows.</p><strong>Recover the appointment</strong></article><article><span>03</span><h3>Care stays unscheduled</h3><p>Patients need timely answers, financing context, and a clear next step.</p><strong>Recover the treatment</strong></article><article><span>04</span><h3>Cash takes too long</h3><p>Insurance friction and patient balances consume staff time.</p><strong>Recover the payment</strong></article></div>
      </section>
      <section className="ad-proof-section"><div className="ads-shell ad-proof-grid"><div className="proof-copy"><span className="ad-kicker">One accountable outcome</span><h2>Not calls answered. <em>Revenue completed.</em></h2><p>RaySky connects the source to the patient, the task, the completed visit, and the financial outcome—so your clinic can verify what changed.</p><a className="ad-secondary" href="/#demo">Explore the recovery model <b>→</b></a></div><div className="proof-card" aria-label="Illustrative clinic recovery report"><div className="proof-card-top"><span><i /> Illustrative clinic</span><small>90-day comparison</small></div><div className="proof-card-main"><span>Production linked to recovered opportunities</span><strong>$43,280</strong><small>Example only · verified from source systems</small></div><div className="proof-stats"><div><strong>74</strong><span>appointments recovered</span></div><div><strong>31</strong><span>completed visits</span></div><div><strong>100%</strong><span>audit trail coverage</span></div></div><div className="proof-path"><span>Patient signal</span><b>→</b><span>Task completed</span><b>→</b><strong>Revenue verified</strong></div></div></div></section>
      <section className="ad-section ads-shell"><header className="ad-section-heading compact"><span>What RaySky completes</span><h2>A revenue recovery team that works inside your systems.</h2></header><div className="outcome-grid"><article><div className="outcome-icon">↗</div><h3>Respond immediately</h3><p>Answer calls, texts, web forms, and after-hours inquiries with the context to complete the next step.</p><ul><li><Check /> New-patient qualification</li><li><Check /> Insurance and payment FAQs</li><li><Check /> Human escalation with context</li></ul></article><article className="featured"><div className="outcome-icon">✓</div><h3>Book correctly</h3><p>Check real-time availability and safely complete the scheduling task in your practice management system.</p><ul><li><Check /> Provider and operatory rules</li><li><Check /> Book, move, or cancel visits</li><li><Check /> Duplicate prevention and writeback</li></ul></article><article><div className="outcome-icon">$</div><h3>Recover what is at risk</h3><p>Follow up on missed demand, overdue care, unscheduled treatment, and eligible balances.</p><ul><li><Check /> Recall and cancellation recovery</li><li><Check /> Treatment coordination</li><li><Check /> Secure payment links</li></ul></article></div></section>
      <section className="ad-clinic-story"><div className="ads-shell clinic-story-grid"><div className="clinic-story-image"><img src="/clinic-collaboration.png" alt="Dental practice team reviewing clinic performance" /></div><div className="clinic-story-copy"><span className="ad-kicker">Built around your front desk</span><h2>Automation for the repeatable work. People for the moments that matter.</h2><p>Your team stays in control. RaySky follows approved policies, escalates clinical and financial exceptions, and hands over the full conversation context.</p><div><span><Check /> No staff re-entry after completed tasks</span><span><Check /> Clear human escalation boundaries</span><span><Check /> Patient-level audit history</span></div></div></div></section>
      <section className="ad-section ads-shell ad-how"><header className="ad-section-heading compact"><span>Start with proof</span><h2>Your recovery assessment in three steps.</h2></header><ol><li><b>01</b><div><h3>Map the leakage</h3><p>Review missed calls, recall, cancellations, treatment, insurance friction, and balances.</p></div></li><li><b>02</b><div><h3>Validate the workflow</h3><p>Confirm PMS access, provider rules, escalation policies, capacity, and your 90-day baseline.</p></div></li><li><b>03</b><div><h3>Launch one measurable play</h3><p>Start with the highest-value opportunity and expand only after your clinic verifies the return.</p></div></li></ol><div className="assessment-includes"><span>Your assessment includes</span><div><strong>Revenue leakage map</strong><strong>Integration readiness</strong><strong>90-day baseline plan</strong><strong>Recommended first workflow</strong></div></div></section>
      <section className="ad-trust"><div className="ads-shell ad-trust-grid"><div><span className="ad-kicker">Healthcare-ready controls</span><h2>Give your team confidence before RaySky speaks with a patient.</h2><p>Access, consent, recordings, retention, escalation, and failure handling are configured around your clinic and market.</p></div><div className="trust-list"><span><Check /> HIPAA / PHIPA-aligned privacy posture</span><span><Check /> Business Associate Agreement availability</span><span><Check /> Role-based permissions and audit logs</span><span><Check /> Consent and opt-out management</span><span><Check /> Configurable recording and retention</span><span><Check /> Human escalation and clinical boundaries</span></div></div></section>
      <section className="ad-section ads-shell ad-faq"><header className="ad-section-heading compact"><span>Common questions</span><h2>What clinic owners ask before getting started.</h2></header><div className="ad-faq-list"><details open><summary>Does RaySky replace our practice management system?<i>+</i></summary><p>No. RaySky is the AI action layer around the systems your team already uses. It reads the information required for the task, writes completed actions back, and preserves the audit trail.</p></details><details><summary>Will patients know they are talking with AI?<i>+</i></summary><p>Your disclosure, consent, recording, and escalation policies are configured during implementation. RaySky is designed to be clear, helpful, and easy to transfer to a person.</p></details><details><summary>How quickly can we see value?<i>+</i></summary><p>The assessment identifies one measurable workflow to launch first. Timing depends on your PMS, policies, data readiness, and chosen workflow; we establish the baseline before measuring results.</p></details><details><summary>How is recovered revenue calculated?<i>+</i></summary><p>RaySky compares completed outcomes with your clinic’s baseline, links each opportunity to its source and patient record, and reports production and collections separately. Illustrative figures on this page are not guarantees.</p></details><details><summary>What happens when RaySky cannot complete a request?<i>+</i></summary><p>It follows your escalation rules and transfers the conversation with the patient context, conversation summary, and recommended next step intact.</p></details></div></section>
      <section className="ad-final-cta"><div className="ads-shell"><span>Start with your clinic’s numbers</span><h2>Find the revenue opportunity your team can recover first.</h2><p>Get a focused assessment of the demand, care, and payment workflows creating the most leakage today.</p><a className="ad-primary" href="#assessment">Get my recovery assessment <b>↗</b></a><small>Focused on measurable outcomes · No patient information required</small></div></section>
      <footer className="ads-footer ads-shell"><a className="ads-brand" href="/"><i>R</i><span>RaySky<small>Dental Revenue OS</small></span></a><p>AI revenue recovery for dental clinics.</p><div><a href="mailto:hello@raysky.ai">Contact</a><a href="/">Full platform</a></div><small>© 2026 RaySky</small></footer>
      <a className="sticky-ad-cta" href="#assessment">Get my free assessment <span>↗</span></a>
    </main>
  );
}
