import type { Metadata } from 'next';
import AuditForm from './AuditForm';
import './blueprint.css';

export const metadata: Metadata = {
  title: 'Stop Losing Clinic Revenue | RaySky AI',
  description: 'Recover missed calls, empty chairs, pending treatment, and marketing opportunities with RaySky’s closed-loop clinic revenue operating system.',
  alternates: { canonical: '/clinic-revenue-audit' },
  openGraph: { title: 'Stop Losing Clinic Revenue to Missed Calls and Empty Chairs', description: 'See how RaySky turns patient opportunities into completed care and measurable revenue.', url: '/clinic-revenue-audit' },
};

const Tick = () => <i className="bp-tick" aria-hidden="true">✓</i>;

export default function ClinicRevenueAuditPage() {
  return <main className="blueprint-page">
    <header className="bp-header"><div className="bp-shell"><a className="bp-brand" href="/"><i>R</i><span>RaySky<small>Clinic Revenue OS</small></span></a><a className="bp-header-cta" href="#audit">Book your free demo <b>↗</b></a></div><div className="bp-trustbar"><span>Seamlessly connects with</span><strong>Dentrix</strong><strong>Eaglesoft</strong><strong>Open Dental</strong><strong>Curve</strong><em><Tick /> Healthcare-ready privacy controls</em></div></header>
    <section className="bp-hero"><div className="bp-shell bp-hero-grid"><div className="bp-hero-copy"><span className="bp-eyebrow">For dental &amp; medical clinics</span><h1>Stop losing clinic revenue to <em>missed calls</em> and empty chairs.</h1><p>RaySky is the automated revenue operating system that helps fill your schedule, follow up on pending care, and prove which marketing opportunities became completed revenue—without adding more repetitive work to your front desk.</p><a className="bp-primary" href="#audit">See how much revenue you could recover <b>↗</b></a><div className="bp-micro"><span><Tick /> No credit card required</span><span><Tick /> Works with your existing systems</span><span><Tick /> Human escalation built in</span></div></div><div><AuditForm /></div></div></section>
    <section className="bp-pain"><div className="bp-shell"><header><span>The hidden cost of manual follow-up</span><h2>Is your clinic leaking revenue every month?</h2><p>You have excellent providers and a trusted practice. But when every patient touchpoint depends on a busy person remembering the next task, valuable opportunities quietly disappear.</p></header><div className="bp-pain-grid"><article><i className="pain-phone">↘</i><h3>Missed opportunities</h3><p>Patients call while the team is serving someone else—or after the clinic closes. Voicemail rarely wins the next available patient.</p><strong>Calls and leads go cold</strong></article><article><i className="pain-chair">□</i><h3>Last-minute openings</h3><p>A cancellation creates valuable chair time, but manually calling a waitlist is too slow and inconsistent.</p><strong>Today’s production disappears</strong></article><article><i className="pain-dollar">$</i><h3>Blind advertising spend</h3><p>Your campaigns create inquiries, but slow response and incomplete attribution make it difficult to know what became care.</p><strong>Leads never become proof</strong></article></div></div></section>
    <section className="bp-outcomes"><div className="bp-shell"><header className="bp-section-head"><span>Enter RaySky</span><h2>Your clinic’s automated <em>revenue completion layer.</em></h2><p>RaySky does more than communicate. It completes the next approved task inside your existing workflow and preserves the outcome for your team.</p></header><div className="bp-outcome-list">
      <article><div className="bp-outcome-copy"><span>Outcome 01 · 24/7 patient capture</span><h3>Turn unanswered demand into booked appointments.</h3><p>RaySky responds to after-hours calls, texts, forms, and campaign inquiries. It qualifies the patient, checks your scheduling rules, and completes the booking when possible.</p><strong><Tick /> More qualified appointments without more repetitive front-desk work</strong></div><div className="bp-ui call-ui"><div className="ui-top"><span><i /> New patient inquiry</span><small>After hours · 8:42 PM</small></div><div className="chat-row patient">Do you have a new-patient exam this week?</div><div className="chat-row agent">Yes—Thursday at 2:30 PM is available with Dr. Patel.</div><div className="ui-result"><Tick /><div><span>Appointment booked</span><strong>Thursday · 2:30 PM</strong></div><small>Written to PMS</small></div></div></article>
      <article><div className="bp-outcome-copy"><span>Outcome 02 · Schedule protection</span><h3>Fill the right opening before chair time is lost.</h3><p>When a patient cancels, RaySky identifies eligible waitlist patients and matches provider, procedure, operatory, and appointment length before outreach begins.</p><strong><Tick /> Less unused capacity and fewer frantic staff calls</strong></div><div className="bp-ui schedule-ui"><div className="ui-top"><span>Wednesday schedule</span><small>Live availability</small></div><div className="slot"><b>1:00</b><span className="filled">Hygiene · Confirmed</span></div><div className="slot active"><b>2:30</b><span><i /> Cancellation detected</span><em>Matching waitlist…</em></div><div className="slot"><b>2:30</b><span className="recovered"><Tick /> Refilled · Maria S.</span></div><div className="ui-footer"><span>Provider ✓</span><span>Procedure ✓</span><span>Length ✓</span></div></div></article>
      <article><div className="bp-outcome-copy"><span>Outcome 03 · Treatment coordination</span><h3>Help patients move from “let me think” to a clear next step.</h3><p>RaySky follows approved treatment workflows, answers policy-controlled questions, shares financing resources, books the next visit, and escalates clinical questions.</p><strong><Tick /> More accepted care with patient-first boundaries</strong></div><div className="bp-ui treatment-ui"><div className="ui-top"><span>Pending treatment</span><small>Opportunity workflow</small></div><div className="treatment-progress"><div><span>Patients eligible</span><strong>48</strong></div><div><span>Contacted</span><strong>31</strong></div><div><span>Booked</span><strong>12</strong></div></div><div className="treatment-bar"><i style={{width:'68%'}} /></div><div className="ui-result"><Tick /><div><span>Financing link viewed</span><strong>Consultation booked</strong></div><small>Human review available</small></div></div></article>
      <article><div className="bp-outcome-copy"><span>Outcome 04 · Source-to-revenue attribution</span><h3>Know which campaigns became completed care.</h3><p>RaySky links the campaign, patient inquiry, booked appointment, attended visit, accepted treatment, and collected revenue into one audit-ready outcome trail.</p><strong><Tick /> Spend against measurable patient and financial outcomes</strong></div><div className="bp-ui attribution-ui"><div className="ui-top"><span>Campaign performance</span><small>Illustrative view</small></div><div className="attribution-value"><span>Completed production</span><strong>$28,450</strong><small>Linked to campaign opportunities</small></div><div className="source-row"><span>Google Search</span><b>$17,900</b></div><div className="source-row"><span>Meta campaign</span><b>$7,850</b></div><div className="source-row"><span>Patient referral</span><b>$2,700</b></div></div></article>
    </div></div></section>
    <section className="bp-integration"><div className="bp-shell bp-integration-grid"><div><span className="bp-kicker">Closed-loop integration</span><h2>No new system for your team to babysit.</h2><p>RaySky works with your existing practice management system. It safely reads the information needed to complete the task and writes the outcome back, according to your configured permissions and rules.</p><a className="bp-dark-cta" href="#audit">Review my integration fit <b>↗</b></a></div><div className="integration-checks"><span><Tick /><div><strong>No manual double-entry</strong><small>Completed tasks and summaries return to the system of record.</small></div></span><span><Tick /><div><strong>Your scheduling rules enforced</strong><small>Providers, operatories, procedures, blocks, and availability.</small></div></span><span><Tick /><div><strong>Auditable write-backs</strong><small>Patient matching, duplicate prevention, and a complete action trail.</small></div></span><span><Tick /><div><strong>Your team stays in control</strong><small>Clinical, insurance, and payment exceptions escalate with context.</small></div></span></div></div><div className="integration-names bp-shell"><strong>Dentrix</strong><strong>Open Dental</strong><strong>Eaglesoft</strong><strong>Curve</strong><strong>Denticon</strong><strong>Cloud 9</strong><span>+ more</span></div></section>
    <section className="bp-proof"><div className="bp-shell bp-proof-grid"><div className="proof-photo"><img src="/treatment-consult.png" alt="Clinician discussing a treatment plan with a patient" /><span>Built to support the patient relationship—not replace it.</span></div><div><span className="bp-kicker">Proof before promises</span><h2>Measure what changed, not what the AI said.</h2><p>Every clinic starts with its own baseline. RaySky tracks the opportunity from source to completed action, then reports production and collections separately.</p><blockquote>“You had 1,240 patient opportunities. 186 were at risk. RaySky recovered 74 appointments—and your clinic can inspect the trail behind every result.”</blockquote><small>Illustrative reporting format. Not a customer testimonial or performance guarantee.</small><div className="proof-points"><span><Tick /> Before-and-after baseline</span><span><Tick /> Source-linked outcomes</span><span><Tick /> Completed production</span><span><Tick /> Separate cash collections</span></div></div></div></section>
    <section className="bp-final"><div className="bp-shell"><span>Free 15-minute revenue audit</span><h2>Ready to find the revenue hiding inside your clinic?</h2><p>See where patient opportunities are being lost, which workflow to fix first, and how RaySky can complete more of the work without overwhelming your team.</p><a className="bp-primary" href="#audit">Book your free revenue audit &amp; demo <b>↗</b></a><small>No credit card · No patient data · No unsupported promises</small></div></section>
    <footer className="bp-footer bp-shell"><a className="bp-brand" href="/"><i>R</i><span>RaySky<small>Clinic Revenue OS</small></span></a><p>AI revenue recovery for dental and medical clinics.</p><div><a href="https://www.raysky.ai/privacy">Privacy policy</a><a href="https://www.raysky.ai/terms">Terms of service</a><a href="mailto:hello@raysky.ai?subject=RaySky%20privacy%20and%20compliance">Privacy &amp; compliance</a></div><small>© 2026 RaySky AI</small></footer>
    <a className="bp-sticky" href="#audit">Book my free revenue audit <b>↗</b></a>
  </main>;
}
