'use client';

import { useEffect, useState } from 'react';

const integrations = ['Dentrix', 'Eaglesoft', 'Open Dental', 'Denticon', 'Curve', 'Cloud 9'];
const foundation = [
  ['01', 'Your PMS, kept up to date', 'RaySky works inside the systems your clinic already uses, so your team does not have to re-enter every call, booking, or follow-up.', ['Real-time availability', 'Provider, operatory & procedure rules', 'Book, reschedule & cancel', 'Patient and family matching', 'Recall, treatment & balance status', 'Chart writeback, duplicate prevention & audit trail']],
  ['02', 'An AI front desk that knows when to ask for help', 'Patients get a fast answer and your staff receive the full context when a person needs to step in.', ['New and existing patient calls', 'Voice, SMS and email conversations', 'Insurance and eligibility questions', 'Digital forms and consent', 'After-hours, cancellations & waitlists', 'Clinical-safe human escalation']],
  ['03', 'A recovery view your team can trust', 'See which opportunities were at risk, what RaySky completed, and what became a booked visit, accepted treatment, or collected balance.', ['Missed calls & unbooked leads', 'Overdue recall & unscheduled treatment', 'Cancellations & waitlist matches', 'Insurance and eligibility friction', 'Outstanding balances and claims follow-up', 'Before-and-after baselines with audit trail']],
];
const workflows = [
  { label: 'Treatment follow-up', title: 'Help patients say yes to the care they already need.', body: 'Identify unaccepted treatment, segment by urgency and procedure, answer approved questions, explain financing options, book the next visit, and stop when the patient opts out or converts.', stat: 'Treatment accepted', tone: 'mint' },
  { label: 'Recall + cancellation recovery', title: 'Keep your schedule full with the right patients.', body: 'Prioritize overdue patients and waitlist opportunities, match provider, procedure, and appointment length, follow up compliantly, and track booked and completed visits.', stat: 'Appointments recovered', tone: 'blue' },
  { label: 'Payments + collections', title: 'Make it easier for patients to resolve balances.', body: 'Send secure payment links, automate balance and failed-payment reminders, prioritize aging accounts, support payment plans, follow claims status, and escalate disputes using approved scripts.', stat: 'Money collected', tone: 'violet' },
];
const growth = ['Google & Meta campaign launch playbooks', 'Dental landing pages and web forms', 'Campaign call tracking and attribution', 'Instant lead-response voice and SMS', 'AI lead qualification', 'Implant, cosmetic, ortho & emergency playbooks', 'Referral, review and service-recovery campaigns', 'Two-way patient texting and email inbox', 'Digital forms, consent and financing options', 'Optional AI smile visualization'];
const trust = ['HIPAA / PHIPA privacy posture', 'Business Associate Agreement', 'Encryption & retention controls', 'Role-based permissions', 'Audit logs', 'Consent & opt-out management', 'Call recording controls', 'Human escalation policies', 'Clinical-safety boundaries', 'Documented AI failure handling', 'Uptime & incident history', 'Owner-ready security documentation'];
const integrationMatrix = [
  ['Dentrix', 'Read + write', 'Appointments, patients, recall, treatment'],
  ['Eaglesoft', 'Read + write', 'Appointments, patients, recall, treatment'],
  ['Open Dental', 'Read + write', 'Appointments, patients, recall, balances'],
  ['Denticon', 'Read + write', 'Multi-location scheduling and reporting'],
  ['Curve / Cloud 9', 'Read + write', 'Appointments, patient matching, summaries'],
];
const demoSteps = [
  { time: '00:02', label: 'Patient intent understood', detail: 'Existing patient needs to reschedule a hygiene visit.' },
  { time: '00:05', label: 'Live rules checked', detail: 'Provider, operatory, procedure length, and availability verified.' },
  { time: '00:12', label: 'Appointment completed', detail: 'New time confirmed and written to the clinic management system.' },
  { time: '00:14', label: 'Lost chair time recovered', detail: 'Released appointment offered to the best-fit waitlist patient.' },
  { time: '00:16', label: 'Outcome documented', detail: 'Confirmation sent, chart summary written, and audit trail closed.' },
];
const platformPillars = [
  ['Recovery', 'Protect the demand you already earned.', 'Missed calls · Recall · Cancellations'],
  ['Growth', 'Convert new interest into attended care.', 'Lead capture · Treatment · Referrals'],
  ['Collections', 'Make balances easier to resolve.', 'Payments · Plans · Claims follow-up'],
  ['Intelligence', 'Know exactly what created production.', 'Attribution · Baselines · Audit trail'],
];
const packages = [
  { name: 'Foundation', monthlyPrice: '$299', yearlyPrice: '$299', yearlyTotal: '$3,588 yearly', setup: '$1,000 setup', description: 'The safe operating layer for every patient conversation.', features: ['Closed-loop Dentrix, Eaglesoft, Open Dental & more', 'Real-time availability and rule-based booking', 'Book, reschedule, cancel and prevent duplicates', 'Patient-record summaries and audit trail', 'AI voice/SMS front desk with human escalation', 'Core calls, bookings and outcome dashboard'] },
  { name: 'Recovery', monthlyPrice: '$599', yearlyPrice: '$599', yearlyTotal: '$7,188 yearly', setup: '$1,500 setup', description: 'Recover missed demand, unused chair time, and overdue patients.', badge: 'Most popular', features: ['Everything in Foundation', 'Missed-call and unbooked-lead recovery', 'Recall and cancellation campaigns', 'Waitlist matching by provider and procedure', 'After-hours and overflow coverage', 'Before-and-after recovery and production reporting'] },
  { name: 'Growth', monthlyPrice: '$999', yearlyPrice: '$999', yearlyTotal: '$11,988 yearly', setup: '$2,000 setup', description: 'Turn treatment, marketing, and collections opportunities into measurable production.', features: ['Everything in Recovery', 'Treatment-plan follow-up and financing options', 'Website chat, forms, email inbox and AI qualification', 'Google/Meta launch playbooks and call tracking', 'Secure payment links, balances, plans and claims follow-up', 'Referrals, reviews and campaign-to-revenue attribution'] },
  { name: 'Enterprise', monthlyPrice: 'Custom', yearlyPrice: 'Custom', setup: 'For groups and DSOs', description: 'Standardize compliant revenue operations across every location.', features: ['Centralized opportunity, production and collections intelligence', 'Multiple PMS integrations, APIs and data feeds', 'Role-based access, SSO, retention and audit controls', 'Custom escalation, consent and recording policies', 'Dedicated implementation, training and success', 'Uptime commitments and security documentation'] },
];
const faqs = [
  ['What do I save with yearly billing?', 'The monthly subscription rate stays the same. With yearly billing, the one-time setup cost is completely waived. The yearly total is billed upfront.'],
  ['How are voice and SMS conversations billed?', 'Voice and SMS are billed separately based on actual usage, so you never pay for credits you do not use. Voice is $0.12 per minute and SMS is $0.025 per message segment. There is no required usage bundle.'],
  ['Which plan is right for my clinic?', 'Foundation is best for clinics that want safe, closed-loop scheduling. Recovery is the best starting point for most clinics because it adds missed-call, recall, cancellation, and lead recovery. Growth adds treatment follow-up and acquisition attribution.'],
  ['What does implementation include?', 'We connect your clinic management system, configure providers, operatories, procedures and escalation rules, prepare approved conversation policies, test the workflows, train your team, and establish your before-and-after baseline.'],
  ['Does RaySky write directly to our practice management system?', 'Yes. Where supported, RaySky reads real-time availability and writes completed actions and summaries back to the system of record. It also applies provider, operatory, procedure, insurance, and duplicate-booking rules configured during implementation.'],
  ['Are payment processing and advertising included?', 'No. Payment processing fees and advertising media spend are separate. This keeps the subscription transparent and lets your clinic maintain control of payment and advertising budgets.'],
  ['Can RaySky transfer a conversation to our team?', 'Yes. RaySky can escalate to a staff member with the patient context, conversation summary, and recommended next step intact. Clinical questions, disputes, and policy exceptions are always routed to the appropriate person.'],
  ['Is RaySky designed for healthcare privacy?', 'RaySky is designed around role-based access, audit logs, consent and opt-out controls, configurable recording and retention, encryption, and human escalation. HIPAA or PHIPA requirements are addressed according to your market and deployment.'],
  ['Do I have to sign a long-term contract?', 'No. Choose monthly billing for flexibility or yearly billing to have the setup cost waived. The subscription rate is the same for both options.'],
];

function Arrow() { return <span aria-hidden="true">↗</span>; }
function Check() { return <span className="check" aria-hidden="true">✓</span>; }

export default function Home() {
  const [yearly, setYearly] = useState(true);
  const [demoRunning, setDemoRunning] = useState(false);
  const [demoStep, setDemoStep] = useState(0);
  useEffect(() => {
    if (!demoRunning) return;
    const timer = window.setInterval(() => {
      setDemoStep(current => {
        if (current >= demoSteps.length - 1) {
          setDemoRunning(false);
          return current;
        }
        return current + 1;
      });
    }, 1100);
    return () => window.clearInterval(timer);
  }, [demoRunning]);
  const runDemo = () => { setDemoStep(0); setDemoRunning(true); };
  return <main>
    <div className="hero-wrap">
    <nav className="nav shell" aria-label="Primary navigation"><a className="brand" href="#top"><span className="brand-mark">R</span><span className="brand-name">RaySky<small>Dental OS</small></span></a><div className="nav-links"><a href="#platform">Platform</a><a href="#growth">Growth</a><a href="#trust">Trust</a><a href="#packages">Pricing</a><a href="#faq">FAQ</a></div><a className="button button-small" href="#demo">See your recovery plan <Arrow /></a></nav>
    <section id="top" className="hero shell cover-hero"><div className="hero-copy"><div className="cover-meta"><span>The Revenue Issue</span><span>Vol. 01 / 2026</span></div><div className="eyebrow"><span className="pulse" /> Cover story · The dental revenue operating system</div><h1><span>Every patient</span><span>opportunity,</span><em>completed.</em></h1><p className="lede">RaySky turns calls, recalls, treatment, cancellations, and balances into completed work—and production your clinic can verify.</p><div className="hero-actions"><a className="button" href="#demo">See your clinic recovery plan <Arrow /></a><a className="text-link" href="#voice-demo">Watch the workflow <span>↓</span></a></div><div className="proof-row"><span><Check /> Closed-loop PMS</span><span><Check /> Human escalation</span><span><Check /> Revenue attribution</span></div></div>
      <div className="hero-stage">
        <span className="hero-orbit orbit-one" aria-hidden="true"/><span className="hero-orbit orbit-two" aria-hidden="true"/><span className="hero-edition">THE PROOF / 01</span>
        <div className="hero-visual" aria-label="RaySky revenue opportunity dashboard preview">
          <div className="dashboard-top"><span className="live"><i /> LIVE OPPORTUNITY VIEW</span><span>Illustrative clinic</span></div>
          <div className="revenue-block"><small>Production attributable to RaySky</small><strong>$184,620</strong><span className="delta">↑ 31.8% vs. baseline</span></div>
          <div className="opportunity-callout waitlist-callout"><span>Waitlist filled</span><strong>+ $1,280</strong></div>
          <div className="chart" aria-hidden="true"><span style={{height:'28%'}}/><span style={{height:'42%'}}/><span style={{height:'37%'}}/><span style={{height:'58%'}}/><span style={{height:'52%'}}/><span style={{height:'75%'}}/><span style={{height:'68%'}}/><span style={{height:'91%'}}/></div>
          <div className="metric-grid"><div><strong>31</strong><span>appointments recovered</span></div><div><strong>$18.4k</strong><span>treatment scheduled</span></div><div><strong>87%</strong><span>recovery lift</span></div></div>
          <div className="opportunity-callout booking-callout"><span>New patient booked</span><strong>Today, 2:30 PM</strong></div>
          <div className="audit-row"><span className="avatar">RS</span><div><strong>Opportunity linked</strong><small>Missed call → appointment → completed production</small></div><span className="status">Verified</span></div>
        </div>
        <div className="cover-folio"><span>RaySky Intelligence</span><i/><span>Patient signal → verified revenue</span></div>
      </div></section>
    </div>
    <section className="integrations-strip"><div className="shell integrations-inner"><span>Closed-loop connections</span>{integrations.map(name => <strong key={name}>{name}</strong>)}<strong>+ more</strong></div></section>
    <section id="voice-demo" className="section shell product-demo"><div className="demo-intro"><span className="kicker">See the system work</span><h2>One patient conversation. Five completed actions.</h2><p>RaySky does more than answer. It checks your rules, completes the task, recovers the newly opened opportunity, updates your systems, and preserves the full audit trail.</p><button className="demo-button" type="button" onClick={runDemo} disabled={demoRunning}><span className={demoRunning?'demo-play active':'demo-play'}>{demoRunning?'•••':'▶'}</span>{demoRunning?'Workflow running':'Run the clinic workflow'}</button><small>Interactive product walkthrough · No phone number required</small></div><div className="demo-console"><div className="demo-console-top"><span><i/> LIVE CLINIC WORKFLOW</span><span>Patient · Hygiene recall</span></div><div className="voice-line"><div className={demoRunning?'wave active':'wave'}>{[12,22,34,18,42,28,48,20,38,25,44,17,31,21,36,14].map((height,index)=><i key={index} style={{height}}/>)}</div><p>“I need to move my cleaning to another afternoon.”</p></div><div className="demo-ledger">{demoSteps.map((step,index)=><div key={step.label} className={index<=demoStep?'demo-ledger-row complete':'demo-ledger-row'}><span>{step.time}</span><i>{index<=demoStep?'✓':String(index+1).padStart(2,'0')}</i><div><strong>{step.label}</strong><small>{step.detail}</small></div></div>)}</div><div className="demo-outcome"><div><span>Workflow outcome</span><strong>{demoStep===demoSteps.length-1?'Completed + verified':'In progress'}</strong></div><div><span>Staff re-entry</span><strong>None</strong></div><div><span>Audit events</span><strong>{demoStep+1} / 5</strong></div></div></div></section>
    <section id="recovery" className="section shell recovery-proof"><div className="section-heading"><div><span className="kicker">Own the measurable middle</span><h2>Every opportunity has a status, an owner, and a financial outcome.</h2></div><p>RaySky connects the patient opportunity to the completed task, attended visit, accepted treatment, and collected revenue.</p></div><div className="equation-grid"><div><small>Patient opportunities</small><strong>1,240</strong></div><span>→</span><div><small>At-risk opportunities</small><strong>186</strong></div><span>→</span><div className="equation-highlight"><small>Appointments recovered</small><strong>74</strong></div><span>→</span><div className="equation-highlight"><small>Production verified</small><strong>$43,280</strong></div></div><div className="proof-labels"><span><Check /> Source-linked to PMS and campaign</span><span><Check /> Before-and-after baseline</span><span><Check /> Audit-ready outcome trail</span></div></section>
    <section className="clinic-visual shell"><div className="clinic-photo"><img src="/clinic-front-desk.png" alt="Dental clinic front desk coordinator reviewing patient activity" /><div className="photo-badge"><span className="pulse" /> RaySky works alongside your front desk</div></div><div className="clinic-visual-copy"><span className="kicker">A calmer clinic day</span><h2>Your team stays focused on patients.</h2><p>RaySky handles the repetitive conversations, updates your systems, and brings the exceptions to the right person with context intact.</p><div className="mini-proof"><span><Check /> Less re-entry</span><span><Check /> Faster follow-up</span><span><Check /> Clear ownership</span></div></div></section>
    <section id="platform" className="section shell"><div className="section-heading"><div><span className="kicker">Built for your clinic</span><h2>The AI front desk that finishes the work.</h2></div><p>RaySky answers patients, completes the task in your system of record, and gives your team a clear next step.</p></div><div className="foundation-grid">{foundation.map(([num,title,body,items]) => <article className="foundation-card" key={String(num)}><span className="number">{String(num)}</span><h3>{String(title)}</h3><p>{String(body)}</p><ul>{(items as string[]).map(item => <li key={item}><Check />{item}</li>)}</ul></article>)}</div></section>
    <section className="section shell integration-matrix-section"><div className="section-heading"><div><span className="kicker">Integration moat</span><h2>Capability matters more than a logo wall.</h2></div><p>For every major PMS, show what RaySky can safely read, write, match, and verify.</p></div><div className="integration-table"><div className="integration-row integration-header"><span>System</span><span>Access</span><span>Workflow coverage</span></div>{integrationMatrix.map(([system,access,coverage])=><div className="integration-row" key={system}><strong>{system}</strong><span className="access-pill">{access}</span><span>{coverage}</span></div>)}</div><p className="integration-note"><Check /> Every supported connector is tested for availability, patient and family matching, provider and operatory rules, insurance and eligibility, recall and treatment status, waitlists, chart summaries, duplicate prevention, and stale-data recovery.</p></section>
    <section className="section section-dark"><div className="shell"><div className="section-heading inverted"><div><span className="kicker">Clinic revenue workflows</span><h2>Keep your schedule full and your balances moving.</h2></div><p>Persistent, policy-controlled follow-up that knows when to book, when to stop, and when your staff should step in.</p></div><div className="workflow-grid">{workflows.map((item,index) => <article className={`workflow-card ${item.tone}`} key={item.label}><div className="workflow-meta"><span>{item.label}</span><b>0{index+1}</b></div><h3>{item.title}</h3><p>{item.body}</p><div className="workflow-outcome"><span>Primary outcome</span><strong>{item.stat}</strong></div></article>)}</div></div></section>
    <section className="section shell human-section"><div className="human-collage"><figure className="human-main"><img src="/clinic-collaboration.png" alt="Dental practice team reviewing clinic performance together"/><figcaption><span>One shared view</span><strong>Your team sees what happened and what comes next.</strong></figcaption></figure><figure className="human-detail"><img src="/treatment-consult.png" alt="Dentist discussing a treatment plan with a patient"/><figcaption><span>Patient-first follow-up</span><strong>Helpful conversations, within your clinic’s policies.</strong></figcaption></figure><div className="collage-stat"><strong>74</strong><span>appointments recovered</span><small>Source-to-production trail verified</small></div></div><div className="human-copy"><span className="kicker">Technology that feels human</span><h2>Better follow-up without losing the personal touch.</h2><p>RaySky handles the repeatable work in the background. Your team remains in control of the moments that need judgment, empathy, or clinical expertise.</p><div className="human-points"><div><span>01</span><p><strong>Context stays intact.</strong><br/>Every handoff includes the conversation, patient status, and recommended next step.</p></div><div><span>02</span><p><strong>Boundaries stay clear.</strong><br/>Clinical, insurance, and payment exceptions always reach the right person.</p></div></div></div></section>
    <section id="growth" className="section shell growth-layout"><div className="growth-copy"><span className="kicker">Bring in the right new patients</span><h2>Fill your schedule, follow up on treatment, and prove what brought them in.</h2><p>RaySky gives your clinic the acquisition tools to respond instantly, then connects each source to the attended appointment, accepted treatment, and collected revenue.</p><blockquote>“We do not just generate leads. We show which campaigns became attended appointments, accepted treatment, and collected revenue.”</blockquote></div><div className="growth-list">{growth.map((item,index) => <div key={item}><span>{String(index+1).padStart(2,'0')}</span><strong>{item}</strong></div>)}</div></section>
    <section id="trust" className="section trust-section"><div className="shell trust-layout"><div><span className="kicker">Patient-first safeguards</span><h2>A safer patient experience for your team and your clinic.</h2><p>See how RaySky handles access, consent, recordings, retention, clinical boundaries, escalations, and failures before you put it in front of patients.</p><a href="#demo" className="text-link light">Request the security brief <Arrow /></a></div><div className="trust-grid">{trust.map(item => <div key={item}><Check /><span>{item}</span></div>)}</div></div></section>
    <section className="section shell system-section">
      <div className="system-heading"><span className="kicker">One revenue operating system</span><h2>Four engines. One accountable outcome.</h2><p>Start with the workflow creating the most leakage today. Expand on the same connected foundation as your clinic proves the return.</p></div>
      <div className="system-stage">
        <div className="system-core"><div><span>RaySky intelligence layer</span><strong>Every patient signal becomes a measurable next action.</strong></div><div className="core-status"><i/> Live · Connected · Auditable</div></div>
        <div className="system-grid">{platformPillars.map(([name,headline,detail],index)=><article key={name}><div className="system-card-top"><span>0{index+1}</span><i/></div><h3>{name}</h3><p>{headline}</p><small>{detail}</small></article>)}</div>
        <div className="system-line"><span>Patient signal</span><i>→</i><span>Policy-controlled action</span><i>→</i><span>Clinic system updated</span><i>→</i><strong>Production verified</strong></div>
      </div>
    </section>
    <section id="packages" className="section shell"><div className="section-heading pricing-heading"><div><span className="kicker">Simple pricing</span><h2>Start where you are. Expand when RaySky proves the return.</h2></div><p>One clear platform fee per location. Every plan includes measurable outcomes, human escalation, and a complete audit trail.</p></div><div className="billing-toggle" aria-label="Billing frequency"><button type="button" className={!yearly?'active':''} onClick={()=>setYearly(false)}>Monthly</button><button type="button" className={yearly?'active':''} onClick={()=>setYearly(true)}>Yearly <span>Best value</span></button></div><div className="package-grid">{packages.map((plan,index) => { const price=yearly?plan.yearlyPrice:plan.monthlyPrice; return <article key={plan.name} className={plan.badge?'package featured':'package'}><div className="package-head"><span>0{index+1}</span>{plan.badge&&<b>{plan.badge}</b>}</div><h3>{plan.name}</h3><div className="package-price"><strong>{price}</strong>{price!=='Custom'&&<span>/month<br/>per location</span>}</div>{yearly&&plan.yearlyTotal&&<small className="billing-total">Billed {plan.yearlyTotal}</small>}<p>{plan.description}</p><small className={`setup ${yearly&&plan.name!=='Enterprise'?'waived':''}`}>{yearly&&plan.name!=='Enterprise'?'✓ Setup waived':plan.setup}</small><ul>{plan.features.map(item=><li key={item}><Check />{item}</li>)}</ul><a href="#demo">Choose {plan.name} <Arrow /></a></article>})}</div><p className="pricing-note">{yearly?'Yearly plans keep the same monthly rate and waive the setup cost. ':'Monthly plans offer maximum flexibility. '}Conversation usage, payments, and advertising are handled separately. <a href="#faq">See common questions</a>.</p></section>
    <section id="faq" className="section faq-section"><div className="shell faq-layout"><div className="faq-intro"><span className="kicker">Frequently asked questions</span><h2>Clear answers before you start.</h2><p>Everything you need to understand implementation, usage, integrations, privacy, and choosing a plan.</p><a className="text-link" href="mailto:hello@raysky.ai?subject=RaySky%20pricing%20question">Ask us a question <Arrow /></a></div><div className="faq-list">{faqs.map(([question,answer],index)=><details key={question} open={index===0}><summary><span>{question}</span><i aria-hidden="true">+</i></summary><p>{answer}</p></details>)}</div></div></section>
    <section className="section shell outcome-banner"><div><span className="kicker">Your clinic, clearly measured</span><h2>See exactly what RaySky recovered.</h2><p>“RaySky recovered 31 appointments worth $18,400 in production.”</p></div><div className="outcome-steps"><span>Patient opportunity</span><i>→</i><span>Task completed</span><i>→</i><span>Revenue verified</span></div></section>
    <section id="demo" className="cta"><div className="shell cta-inner"><div><span className="kicker">Find your first revenue workflow</span><h2>See what RaySky could recover for your clinic.</h2><p>Bring your missed-call volume, overdue recall, unbooked treatment, or aging balances. We’ll map the workflow and the outcome your team can verify.</p></div><a className="button button-light" href="mailto:hello@raysky.ai?subject=RaySky%20recovery%20plan">Book a clinic walkthrough <Arrow /></a></div></section>
    <footer className="footer shell"><a className="brand" href="#top"><span className="brand-mark">R</span><span className="brand-name">RaySky<small>Dental OS</small></span></a><p>AI revenue recovery for dental clinics.</p><div><a href="#platform">Platform</a><a href="#trust">Trust</a><a href="mailto:hello@raysky.ai">Contact</a></div><small>© 2026 RaySky. All rights reserved.</small></footer>
  </main>;
}
