'use client';

import { useState } from 'react';

const integrations = ['Dentrix', 'Eaglesoft', 'Open Dental', 'Denticon', 'Curve', 'Cloud 9'];
const foundation = [
  ['01', 'Closed-loop PMS integrations', 'Read and write safely across your practice systems—without duplicate entry or fragile workarounds.', ['Real-time availability', 'Book, reschedule & cancel', 'Provider, operatory & procedure rules', 'Patient-record writeback', 'Recall, treatment & balance status', 'Duplicate prevention & audit trail']],
  ['02', 'AI front desk + human escalation', 'Voice and SMS agents complete the work, then hand off with the full conversation and next step intact.', ['New and existing patient calls', 'Scheduling, cancellations & waitlists', 'Insurance and payment FAQs', 'Treatment follow-up', 'After-hours and overflow', 'Context-preserving escalation']],
  ['03', 'Revenue opportunity dashboard', 'Connect every conversation to booked appointments, accepted treatment, collections, and attributable production.', ['Missed calls & unbooked leads', 'Overdue recall & unscheduled treatment', 'Cancellations & unpaid balances', 'Insurance verification issues', 'Before-and-after baselines', 'Opportunity-level audit trail']],
];
const workflows = [
  { label: 'Treatment follow-up', title: 'Move diagnosed care from “maybe” to scheduled.', body: 'Identify unaccepted treatment, segment by urgency and procedure, answer approved questions, present financing information, book the next visit, and stop when the patient opts out or converts.', stat: 'Treatment accepted', tone: 'mint' },
  { label: 'Recall + cancellation recovery', title: 'Keep productive chair time from slipping away.', body: 'Prioritize overdue patients and waitlist opportunities, match provider and appointment requirements, follow up compliantly, and track both booked and completed visits.', stat: 'Appointments recovered', tone: 'blue' },
  { label: 'Payments + collections', title: 'Make it easier to resolve balances securely.', body: 'Send Stripe payment links, automate balance and failed-payment reminders, prioritize aging accounts, support payment plans, and escalate disputes—using controlled scripts, never improvised advice.', stat: 'Money collected', tone: 'violet' },
];
const growth = ['Google & Meta campaign templates', 'Dental-specific landing pages', 'Website chat and form capture', 'Instant SMS and voice response', 'Campaign-to-appointment attribution', 'Implant, cosmetic, ortho & emergency playbooks', 'Referral and review campaigns', 'Optional AI smile visualization'];
const trust = ['HIPAA / PHIPA privacy posture', 'Business Associate Agreement', 'Encryption & retention controls', 'Role-based permissions', 'Audit logs', 'Consent & opt-out management', 'Call recording controls', 'Human escalation policies', 'Uptime & incident history', 'Owner-ready security documentation'];
const packages = [
  { name: 'Foundation', monthlyPrice: '$299', yearlyPrice: '$299', yearlyTotal: '$3,588 yearly', setup: '$1,000 setup', description: 'The safe operating layer for every patient conversation.', features: ['Closed-loop Dentrix, Eaglesoft, Open Dental & more', 'Real-time availability and rule-based booking', 'Book, reschedule, cancel and prevent duplicates', 'Patient-record summaries and audit trail', 'AI voice/SMS front desk with human escalation', 'Core calls, bookings and outcome dashboard'] },
  { name: 'Recovery', monthlyPrice: '$599', yearlyPrice: '$599', yearlyTotal: '$7,188 yearly', setup: '$1,500 setup', description: 'Recover missed demand, unused chair time, and overdue patients.', badge: 'Most popular', features: ['Everything in Foundation', 'Missed-call and unbooked-lead recovery', 'Recall and cancellation campaigns', 'Waitlist matching by provider and procedure', 'After-hours and overflow coverage', 'Before-and-after recovery and production reporting'] },
  { name: 'Growth', monthlyPrice: '$999', yearlyPrice: '$999', yearlyTotal: '$11,988 yearly', setup: '$2,000 setup', description: 'Turn treatment, marketing, and collections opportunities into revenue.', features: ['Everything in Recovery', 'Personalized treatment-plan follow-up', 'Website chat, forms and instant lead response', 'Google/Meta playbooks and campaign attribution', 'Secure payment links, balances and payment plans', 'Referrals, reviews and accepted-treatment reporting'] },
  { name: 'Enterprise', monthlyPrice: 'Custom', yearlyPrice: 'Custom', setup: 'For groups and DSOs', description: 'Standardize compliant revenue operations across every location.', features: ['Centralized opportunity, production and collections intelligence', 'Multiple PMS integrations, APIs and data feeds', 'Role-based access, SSO, retention and audit controls', 'Custom escalation, consent and recording policies', 'Dedicated implementation, training and success', 'Uptime commitments and security documentation'] },
];
const faqs = [
  ['What do I save with yearly billing?', 'The monthly subscription rate stays the same. With yearly billing, the one-time setup cost is completely waived. The yearly total is billed upfront.'],
  ['How are voice and SMS conversations billed?', 'Voice and SMS are billed separately based on actual usage, so you never pay for credits you do not use. Voice is $0.12 per minute and SMS is $0.025 per message segment. There is no required usage bundle.'],
  ['Which plan is right for my practice?', 'Foundation is best for practices that want safe, closed-loop scheduling. Recovery is the best starting point for most practices because it adds missed-call, recall, cancellation, and lead recovery. Growth adds treatment follow-up and demand-generation attribution.'],
  ['What does implementation include?', 'We connect your practice management system, configure providers, operatories, procedures and escalation rules, prepare approved conversation policies, test the workflows, train your team, and establish your before-and-after baseline.'],
  ['Does RaySky write directly to our practice management system?', 'Yes. Where supported, RaySky reads real-time availability and writes completed actions and summaries back to the system of record. It also applies provider, operatory, procedure, insurance, and duplicate-booking rules configured during implementation.'],
  ['Are payment processing and advertising included?', 'No. Payment processing fees and advertising media spend are separate. This keeps the subscription transparent and lets your practice maintain control of payment and advertising budgets.'],
  ['Can RaySky transfer a conversation to our team?', 'Yes. RaySky can escalate to a staff member with the patient context, conversation summary, and recommended next step intact. Clinical questions, disputes, and policy exceptions are always routed to the appropriate person.'],
  ['Is RaySky designed for healthcare privacy?', 'RaySky is designed around role-based access, audit logs, consent and opt-out controls, configurable recording and retention, encryption, and human escalation. HIPAA or PHIPA requirements are addressed according to your market and deployment.'],
  ['Do I have to sign a long-term contract?', 'No. Choose monthly billing for flexibility or yearly billing to have the setup cost waived. The subscription rate is the same for both options.'],
];

function Arrow() { return <span aria-hidden="true">↗</span>; }
function Check() { return <span className="check" aria-hidden="true">✓</span>; }

export default function Home() {
  const [yearly, setYearly] = useState(true);
  return <main>
    <nav className="nav shell" aria-label="Primary navigation"><a className="brand" href="#top"><span className="brand-mark">R</span><span>RaySky</span></a><div className="nav-links"><a href="#platform">Platform</a><a href="#growth">Growth</a><a href="#trust">Trust</a><a href="#packages">Pricing</a><a href="#faq">FAQ</a></div><a className="button button-small" href="#demo">See your recovery plan <Arrow /></a></nav>
    <section id="top" className="hero shell"><div className="hero-copy"><div className="eyebrow"><span className="pulse" /> The dental revenue operating system</div><h1>From every patient conversation to <em>collected revenue.</em></h1><p className="lede">RaySky connects your phone, text, practice management system, campaigns, and payments—so the work gets completed, the outcome gets measured, and your team never has to re-enter the result.</p><div className="hero-actions"><a className="button" href="#demo">Build your recovery plan <Arrow /></a><a className="text-link" href="#platform">Explore the platform <span>↓</span></a></div><div className="proof-row"><span><Check /> Closed-loop PMS</span><span><Check /> Voice + SMS</span><span><Check /> Revenue attribution</span></div></div>
      <div className="hero-visual" aria-label="RaySky revenue opportunity dashboard preview"><div className="dashboard-top"><span className="live"><i /> LIVE OPPORTUNITY VIEW</span><span>Last 30 days</span></div><div className="revenue-block"><small>Production attributable to RaySky</small><strong>$184,620</strong><span className="delta">↑ 31.8% vs. baseline</span></div><div className="chart" aria-hidden="true"><span style={{height:'28%'}}/><span style={{height:'42%'}}/><span style={{height:'37%'}}/><span style={{height:'58%'}}/><span style={{height:'52%'}}/><span style={{height:'75%'}}/><span style={{height:'68%'}}/><span style={{height:'91%'}}/></div><div className="metric-grid"><div><strong>31</strong><span>appointments recovered</span></div><div><strong>$18.4k</strong><span>treatment scheduled</span></div><div><strong>87%</strong><span>recovery lift</span></div></div><div className="audit-row"><span className="avatar">RS</span><div><strong>Opportunity linked</strong><small>Missed call → appointment → completed production</small></div><span className="status">Verified</span></div></div></section>
    <section className="integrations-strip"><div className="shell integrations-inner"><span>Closed-loop connections</span>{integrations.map(name => <strong key={name}>{name}</strong>)}<strong>+ more</strong></div></section>
    <section id="platform" className="section shell"><div className="section-heading"><div><span className="kicker">Competitive MVP</span><h2>The operational core other AI receptionists leave unfinished.</h2></div><p>RaySky does not stop when a conversation ends. It completes the task in the system of record and proves the business result.</p></div><div className="foundation-grid">{foundation.map(([num,title,body,items]) => <article className="foundation-card" key={String(num)}><span className="number">{String(num)}</span><h3>{String(title)}</h3><p>{String(body)}</p><ul>{(items as string[]).map(item => <li key={item}><Check />{item}</li>)}</ul></article>)}</div></section>
    <section className="section section-dark"><div className="shell"><div className="section-heading inverted"><div><span className="kicker">Always-on recovery engine</span><h2>Three workflows that compound revenue every month.</h2></div><p>Persistent, policy-controlled outreach that knows when to book, when to stop, and when a human needs to step in.</p></div><div className="workflow-grid">{workflows.map((item,index) => <article className={`workflow-card ${item.tone}`} key={item.label}><div className="workflow-meta"><span>{item.label}</span><b>0{index+1}</b></div><h3>{item.title}</h3><p>{item.body}</p><div className="workflow-outcome"><span>Primary outcome</span><strong>{item.stat}</strong></div></article>)}</div></div></section>
    <section id="growth" className="section shell growth-layout"><div className="growth-copy"><span className="kicker">Close the demand-generation gap</span><h2>Generate demand. Respond instantly. Prove what became revenue.</h2><p>RaySky pairs dental campaign playbooks with closed-loop practice data, so marketing performance is measured at the attended appointment, accepted treatment, and collected revenue—not just the lead form.</p><blockquote>“We do not just generate leads. We show which campaigns became attended appointments, accepted treatment, and collected revenue.”</blockquote></div><div className="growth-list">{growth.map((item,index) => <div key={item}><span>{String(index+1).padStart(2,'0')}</span><strong>{item}</strong></div>)}</div></section>
    <section id="trust" className="section trust-section"><div className="shell trust-layout"><div><span className="kicker">Healthcare-grade trust layer</span><h2>Trust should be visible before the first sales call.</h2><p>Give practice owners, operators, and privacy teams a clear path to verify how RaySky handles patient conversations, access, consent, recordings, retention, and incidents.</p><a href="#demo" className="text-link light">Request the security brief <Arrow /></a></div><div className="trust-grid">{trust.map(item => <div key={item}><Check /><span>{item}</span></div>)}</div></div></section>
    <section id="packages" className="section shell"><div className="section-heading pricing-heading"><div><span className="kicker">Simple pricing</span><h2>Start where you are. Expand when RaySky proves the return.</h2></div><p>One clear platform fee per location. Every plan includes measurable outcomes, human escalation, and a complete audit trail.</p></div><div className="billing-toggle" aria-label="Billing frequency"><button type="button" className={!yearly?'active':''} onClick={()=>setYearly(false)}>Monthly</button><button type="button" className={yearly?'active':''} onClick={()=>setYearly(true)}>Yearly <span>Best value</span></button></div><div className="package-grid">{packages.map((plan,index) => { const price=yearly?plan.yearlyPrice:plan.monthlyPrice; return <article key={plan.name} className={plan.badge?'package featured':'package'}><div className="package-head"><span>0{index+1}</span>{plan.badge&&<b>{plan.badge}</b>}</div><h3>{plan.name}</h3><div className="package-price"><strong>{price}</strong>{price!=='Custom'&&<span>/month<br/>per location</span>}</div>{yearly&&plan.yearlyTotal&&<small className="billing-total">Billed {plan.yearlyTotal}</small>}<p>{plan.description}</p><small className={`setup ${yearly&&plan.name!=='Enterprise'?'waived':''}`}>{yearly&&plan.name!=='Enterprise'?'✓ Setup waived':plan.setup}</small><ul>{plan.features.map(item=><li key={item}><Check />{item}</li>)}</ul><a href="#demo">Choose {plan.name} <Arrow /></a></article>})}</div><p className="pricing-note">{yearly?'Yearly plans keep the same monthly rate and waive the setup cost. ':'Monthly plans offer maximum flexibility. '}Conversation usage, payments, and advertising are handled separately. <a href="#faq">See common questions</a>.</p></section>
    <section id="faq" className="section faq-section"><div className="shell faq-layout"><div className="faq-intro"><span className="kicker">Frequently asked questions</span><h2>Clear answers before you start.</h2><p>Everything you need to understand implementation, usage, integrations, privacy, and choosing a plan.</p><a className="text-link" href="mailto:hello@raysky.ai?subject=RaySky%20pricing%20question">Ask us a question <Arrow /></a></div><div className="faq-list">{faqs.map(([question,answer],index)=><details key={question} open={index===0}><summary><span>{question}</span><i aria-hidden="true">+</i></summary><p>{answer}</p></details>)}</div></div></section>
    <section className="section shell outcome-banner"><div><span className="kicker">The metric that matters</span><h2>Not “AI answered 98% of calls.”</h2><p>“RaySky recovered 31 appointments worth $18,400 in production.”</p></div><div className="outcome-steps"><span>Conversation</span><i>→</i><span>Task completed</span><i>→</i><span>Revenue verified</span></div></section>
    <section id="demo" className="cta"><div className="shell cta-inner"><div><span className="kicker">Find your first revenue workflow</span><h2>See what RaySky could recover in your practice.</h2><p>Bring your missed-call volume, overdue recall, unscheduled treatment, or aging balances. We’ll map the workflow and the attributable outcome.</p></div><a className="button button-light" href="mailto:hello@raysky.ai?subject=RaySky%20recovery%20plan">Book a strategy call <Arrow /></a></div></section>
    <footer className="footer shell"><a className="brand" href="#top"><span className="brand-mark">R</span><span>RaySky</span></a><p>The dental revenue operating system.</p><div><a href="#platform">Platform</a><a href="#trust">Trust</a><a href="mailto:hello@raysky.ai">Contact</a></div><small>© 2026 RaySky. All rights reserved.</small></footer>
  </main>;
}
